// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONSOLE_H
#define CONSOLE_H

#include <wx/wx.h>
#include "Room.h"
#include "User.h"
#include "OwnerUser.h"
#include "PermanentUser.h"
#include "TemporaryUser.h"

/*
 * Consoles control Sensors.
 */
class Console
{
	public:
		Console();
		~Console();
		
		//buffer opperations
		void BufferEnter(char input);
		wxString GetBuffer();
		void BufferClear();
		
		//checking sensors
		void CheckSensors(wxString* inNames, bool ** output);
        
        bool TripG(int inSensorType);
        bool TripF(int inSensorType);
        bool TripK(int inSensorType);
        bool TripD(int inSensorType);
        bool TripBed(int inSensorType);
        bool TripBath(int inSensorType);
        bool TripO(int inSensorType);

        bool ResetG(int inSensorType);
        bool ResetF(int inSensorType);
        bool ResetK(int inSensorType);
        bool ResetD(int inSensorType);
        bool ResetBed(int inSensorType);
        bool ResetBath(int inSensorType);
        bool ResetO(int inSensorType);
        
        bool ResetSystem();
        
        void OnSystemError();
        bool GetSystemError();

    protected:
        wxString Output;
        static bool SystemError;
        static bool PriSystemReseted;
        static bool SecSystemReseted;

        //all the rooms in the house
        static Room G;
        static Room F;
        static Room K;
        static Room D;
        static Room Bed;
        static Room Bath;
        static Room O;

        //logging in and out
        bool Login(wxString inCode);
        bool Logout();

        //used to keep track of which user is logged in
        int UserType;
        int pointer;

        //all the user accounts
        static OwnerUser OwnerAccount;

        static PermanentUser ** PermanentAccounts;
        static int PermCount;
        
        static TemporaryUser ** TemporaryAccounts;
        static int TempCount;

        static wxString OwnerCode;
        wxString BufferString;
};

#endif // CONSOLE_H
