// Class automatically generated by Dev-C++ New Class wizard

#ifndef PRIMARYCONSOLE_H
#define PRIMARYCONSOLE_H

#include <wx/wx.h>
#include "Room.h"
#include "Console.h" // inheriting class's header file

/*
 * Allows the OwnerUser and PermanentUsers to Enable/Disable Sensors.
 */
class PrimaryConsole : public Console
{
	public:
		PrimaryConsole();
		~PrimaryConsole();

        void OwnerMenu();
        void PermanentMenu();

        void Settings();
            void UpdateUsers();
                void UUSelectPerm();
                void UUSelectTemp();
                    void UUGetStartHour();
                    void UUGetStartMinute();
                    void UUGetEndHour();
                    void UUGetEndMinute();
                void ChangeCodeOwner();
                void ChangeCodePerm();
                void ChangeCodeTemp();
            void AddRemoveUsers();
                void AddPerm();
                void AddTemp();
                    void GetStartHour();
                    void GetStartMinute();
                    void GetEndHour();
                    void GetEndMinute();
                void RemovePerm();
                void RemoveTemp();

        void SelectRoom();
		void SelectSensor();
        void EnableDisable();
		void EnableSensor();
		void DisableSensor();

		void PriLogin();
		void PriLogout();
        wxString GetOutput();
		
        wxString currentRoom;
        int SensorType;
        
        int removePointer;
        
        void DoNextAction();
        wxString nextAction;
        wxString tempCode;
        int tempTime;
        int tempHour;
        int tempMinute;
        TemporaryUser *TempPtr;
        
        //creating user accounts
        void CreatePermUser(wxString inCode);
        void CreateTempUser(wxString inCode, int startTime = 0, int endTime = 0);
        
    private:
        void DisplayOwner();
        void DisplayPermanent();
        void DisplaySettings();
        void DisplayUpdateUser();
        void DisplayAddRemoveUser();
        void DisplaySelectRoom();
        void DisplaySelectSensor();
        void DisplayEnableDisable();
        void DisplayAllPerm();
        void DisplayAllTemp();
};

#endif // PRIMARYCONSOLE_H
